In [1]:
import numpy as np
import pandas as pd
from utils import get_data_as_list

In [2]:
data_list = get_data_as_list(day=1)
data_list

In [3]:
data_list

['134',
 '138',
 '142',
 '143',
 '141',
 '142',
 '145',
 '140',
 '144',
 '156',
 '158',
 '163',
 '164',
 '170',
 '192',
 '193',
 '194',
 '218',
 '216',
 '229',
 '210',
 '212',
 '217',
 '219',
 '252',
 '254',
 '253',
 '256',
 '257',
 '258',
 '259',
 '270',
 '271',
 '273',
 '289',
 '314',
 '289',
 '315',
 '321',
 '330',
 '331',
 '307',
 '316',
 '325',
 '326',
 '330',
 '344',
 '347',
 '330',
 '342',
 '344',
 '337',
 '338',
 '341',
 '345',
 '347',
 '364',
 '394',
 '395',
 '418',
 '421',
 '422',
 '425',
 '426',
 '434',
 '432',
 '442',
 '443',
 '445',
 '446',
 '459',
 '460',
 '469',
 '464',
 '449',
 '466',
 '484',
 '485',
 '488',
 '489',
 '495',
 '499',
 '501',
 '504',
 '505',
 '508',
 '520',
 '530',
 '535',
 '537',
 '533',
 '534',
 '538',
 '539',
 '542',
 '544',
 '545',
 '546',
 '547',
 '565',
 '566',
 '579',
 '586',
 '596',
 '601',
 '602',
 '615',
 '623',
 '625',
 '626',
 '641',
 '645',
 '654',
 '657',
 '659',
 '658',
 '661',
 '678',
 '680',
 '682',
 '673',
 '682',
 '686',
 '689',
 '694',
 '704',
 '705',
 '706',
 '734',
 '735',
 '741',
 '746',
 '747',
 '756',
 '772',
 '773',
 '806',
 '807',
 '819',
 '820',
 '824',
 '837',
 '835',
 '837',
 '834',
 '842',
 '844',
 '860',
 '855',
 '862',
 '863',
 '873',
 '898',
 '904',
 '908',
 '909',
 '910',
 '911',
 '921',
 '922',
 '928',
 '930',
 '943',
 '949',
 '951',
 '947',
 '953',
 '963',
 '965',
 '967',
 '970',
 '975',
 '976',
 '979',
 '986',
 '1009',
 '1017',
 '1021',
 '1022',
 '1047',
 '1073',
 '1075',
 '1100',
 '1101',
 '1136',
 '1143',
 '1149',
 '1148',
 '1149',
 '1150',
 '1154',
 '1167',
 '1169',
 '1175',
 '1178',
 '1181',
 '1191',
 '1194',
 '1195',
 '1196',
 '1203',
 '1204',
 '1188',
 '1196',
 '1197',
 '1198',
 '1211',
 '1213',
 '1221',
 '1225',
 '1227',
 '1232',
 '1233',
 '1244',
 '1245',
 '1251',
 '1252',
 '1253',
 '1254',
 '1281',
 '1292',
 '1293',
 '1296',
 '1306',
 '1320',
 '1312',
 '1313',
 '1318',
 '1319',
 '1322',
 '1323',
 '1324',
 '1344',
 '1345',
 '1348',
 '1354',
 '1357',
 '1356',
 '1359',
 '1360',
 '1362',
 '1363',
 '1364',
 '1366',
 '1384',
 '1388',
 '1389',
 '1388',
 '1390',
 '1391',
 '1412',
 '1415',
 '1416',
 '1415',
 '1414',
 '1424',
 '1429',
 '1430',
 '1453',
 '1459',
 '1470',
 '1472',
 '1491',
 '1494',
 '1499',
 '1497',
 '1498',
 '1491',
 '1496',
 '1497',
 '1496',
 '1523',
 '1527',
 '1532',
 '1525',
 '1555',
 '1559',
 '1576',
 '1586',
 '1593',
 '1609',
 '1610',
 '1612',
 '1619',
 '1645',
 '1650',
 '1657',
 '1677',
 '1705',
 '1706',
 '1709',
 '1713',
 '1722',
 '1737',
 '1773',
 '1783',
 '1795',
 '1796',
 '1807',
 '1806',
 '1807',
 '1808',
 '1828',
 '1829',
 '1835',
 '1837',
 '1845',
 '1848',
 '1847',
 '1854',
 '1862',
 '1860',
 '1861',
 '1862',
 '1863',
 '1868',
 '1882',
 '1892',
 '1904',
 '1876',
 '1875',
 '1877',
 '1907',
 '1922',
 '1936',
 '1932',
 '1938',
 '1948',
 '1950',
 '1953',
 '1955',
 '1957',
 '1958',
 '1956',
 '1961',
 '1966',
 '1964',
 '1968',
 '1987',
 '1984',
 '1988',
 '1990',
 '1991',
 '2009',
 '2012',
 '2018',
 '2022',
 '2041',
 '2042',
 '2057',
 '2058',
 '2056',
 '2064',
 '2070',
 '2073',
 '2077',
 '2080',
 '2041',
 '2044',
 '2042',
 '2045',
 '2053',
 '2052',
 '2054',
 '2055',
 '2058',
 '2064',
 '2068',
 '2067',
 '2078',
 '2086',
 '2085',
 '2090',
 '2093',
 '2108',
 '2109',
 '2110',
 '2118',
 '2114',
 '2121',
 '2124',
 '2125',
 '2111',
 '2112',
 '2126',
 '2127',
 '2138',
 '2141',
 '2153',
 '2158',
 '2170',
 '2161',
 '2162',
 '2163',
 '2164',
 '2165',
 '2175',
 '2196',
 '2205',
 '2210',
 '2209',
 '2210',
 '2218',
 '2234',
 '2254',
 '2255',
 '2266',
 '2267',
 '2269',
 '2270',
 '2274',
 '2276',
 '2263',
 '2264',
 '2266',
 '2267',
 '2264',
 '2267',
 '2276',
 '2283',
 '2284',
 '2287',
 '2298',
 '2299',
 '2309',
 '2310',
 '2321',
 '2322',
 '2323',
 '2328',
 '2330',
 '2333',
 '2336',
 '2366',
 '2367',
 '2368',
 '2365',
 '2371',
 '2372',
 '2373',
 '2371',
 '2375',
 '2376',
 '2373',
 '2379',
 '2380',
 '2382',
 '2392',
 '2394',
 '2398',
 '2420',
 '2427',
 '2438',
 '2439',
 '2440',
 '2441',
 '2452',
 '2453',
 '2478',
 '2482',
 '2484',
 '2495',
 '2510',
 '2514',
 '2516',
 '2531',
 '2536',
 '2563',
 '2564',
 '2559',
 '2585',
 '2599',
 '2608',
 '2613',
 '2611',
 '2619',
 '2633',
 '2644',
 '2645',
 '2646',
 '2649',
 '2632',
 '2649',
 '2656',
 '2651',
 '2663',
 '2678',
 '2684',
 '2682',
 '2684',
 '2685',
 '2686',
 '2687',
 '2708',
 '2709',
 '2718',
 '2720',
 '2721',
 '2727',
 '2733',
 '2751',
 '2740',
 '2742',
 '2749',
 '2748',
 '2750',
 '2780',
 '2757',
 '2762',
 '2760',
 '2771',
 '2758',
 '2777',
 '2781',
 '2785',
 '2787',
 '2812',
 '2825',
 '2830',
 '2838',
 '2840',
 '2852',
 '2857',
 '2862',
 '2865',
 '2847',
 '2846',
 '2847',
 '2848',
 '2849',
 '2852',
 '2854',
 '2859',
 '2868',
 '2870',
 '2872',
 '2873',
 '2882',
 '2889',
 '2890',
 '2893',
 '2890',
 '2891',
 '2895',
 '2901',
 '2907',
 '2911',
 '2912',
 '2920',
 '2921',
 '2925',
 '2924',
 '2942',
 '2952',
 '2961',
 '2965',
 '2964',
 '2978',
 '2981',
 '2992',
 '3010',
 '3005',
 '3019',
 '3013',
 '3015',
 '3019',
 '3022',
 '3024',
 '3027',
 '3037',
 '3038',
 '3041',
 '3043',
 '3047',
 '3065',
 '3075',
 '3083',
 '3092',
 '3093',
 '3117',
 '3118',
 '3119',
 '3125',
 '3126',
 '3130',
 '3145',
 '3137',
 '3149',
 '3153',
 '3154',
 '3155',
 '3180',
 '3182',
 '3183',
 '3182',
 '3200',
 '3202',
 '3214',
 '3197',
 '3207',
 '3185',
 '3203',
 '3208',
 '3209',
 '3208',
 '3231',
 '3233',
 '3234',
 '3242',
 '3255',
 '3256',
 '3257',
 '3258',
 '3265',
 '3268',
 '3290',
 '3291',
 '3297',
 '3311',
 '3301',
 '3309',
 '3314',
 '3317',
 '3319',
 '3320',
 '3337',
 '3347',
 '3362',
 '3376',
 '3390',
 '3404',
 '3412',
 '3417',
 '3418',
 '3421',
 '3425',
 '3436',
 '3438',
 '3439',
 '3453',
 '3467',
 '3484',
 '3485',
 '3486',
 '3515',
 '3516',
 '3521',
 '3527',
 '3534',
 '3551',
 '3561',
 '3572',
 '3573',
 '3574',
 '3596',
 '3612',
 '3595',
 '3616',
 '3617',
 '3619',
 '3620',
 '3624',
 '3634',
 '3657',
 '3663',
 '3671',
 '3686',
 '3687',
 '3694',
 '3704',
 '3695',
 '3697',
 '3698',
 '3699',
 '3700',
 '3701',
 '3702',
 '3704',
 '3705',
 '3707',
 '3716',
 '3717',
 '3732',
 '3747',
 '3748',
 '3745',
 '3746',
 '3748',
 '3756',
 '3757',
 '3764',
 '3765',
 '3766',
 '3768',
 '3784',
 '3807',
 '3810',
 '3805',
 '3811',
 '3812',
 '3813',
 '3828',
 '3840',
 '3847',
 '3848',
 '3851',
 '3850',
 '3851',
 '3855',
 '3861',
 '3862',
 '3867',
 '3864',
 '3871',
 '3879',
 '3884',
 '3885',
 '3887',
 '3888',
 '3928',
 '3948',
 '3949',
 '3950',
 '3960',
 '3959',
 '3965',
 '3973',
 '3970',
 '3971',
 '3972',
 '3974',
 '3969',
 '3997',
 '3998',
 '4014',
 '4016',
 '4017',
 '4026',
 '4039',
 '4043',
 '4052',
 '4053',
 '4051',
 '4054',
 '4058',
 '4066',
 '4067',
 '4073',
 '4077',
 '4084',
 '4072',
 '4078',
 '4083',
 '4094',
 '4101',
 '4107',
 '4115',
 '4138',
 '4141',
 '4143',
 '4166',
 '4177',
 '4184',
 '4194',
 '4192',
 '4198',
 '4203',
 '4204',
 '4209',
 '4215',
 '4217',
 '4226',
 '4231',
 '4252',
 '4253',
 '4260',
 '4294',
 '4306',
 '4307',
 '4314',
 '4316',
 '4317',
 '4325',
 '4326',
 '4334',
 '4344',
 '4348',
 '4344',
 '4348',
 '4350',
 '4358',
 '4383',
 '4384',
 '4390',
 '4383',
 '4378',
 '4374',
 '4377',
 '4398',
 '4399',
 '4431',
 '4432',
 '4433',
 '4432',
 '4443',
 '4441',
 '4442',
 '4443',
 '4439',
 '4441',
 '4444',
 '4445',
 '4446',
 '4449',
 '4452',
 '4458',
 '4463',
 '4469',
 '4472',
 '4475',
 '4478',
 '4491',
 '4504',
 '4507',
 '4509',
 '4510',
 '4511',
 '4513',
 '4525',
 '4532',
 '4533',
 '4541',
 '4552',
 '4551',
 '4552',
 '4573',
 '4594',
 '4597',
 '4601',
 '4602',
 '4617',
 '4621',
 '4622',
 '4621',
 '4601',
 '4604',
 '4606',
 '4607',
 '4611',
 '4591',
 '4604',
 '4608',
 '4615',
 '4613',
 '4621',
 '4625',
 '4642',
 '4637',
 '4641',
 '4659',
 '4674',
 '4678',
 '4680',
 '4700',
 '4701',
 '4702',
 '4703',
 '4706',
 '4712',
 '4699',
 '4701',
 '4704',
 '4706',
 '4707',
 '4714',
 '4717',
 '4721',
 '4722',
 '4731',
 '4735',
 '4748',
 '4749',
 '4753',
 '4757',
 '4779',
 '4783',
 '4788',
 '4790',
 '4791',
 '4794',
 '4813',
 '4814',
 '4815',
 '4801',
 '4803',
 '4806',
 '4807',
 '4837',
 '4838',
 '4842',
 '4844',
 '4854',
 '4855',
 '4859',
 '4856',
 '4847',
 '4849',
 '4850',
 '4852',
 '4866',
 '4868',
 '4880',
 '4902',
 '4901',
 '4905',
 '4909',
 '4921',
 '4922',
 '4939',
 '4920',
 '4922',
 '4938',
 '4944',
 '4947',
 '4948',
 '4960',
 '4961',
 '4971',
 '4986',
 '4992',
 '4996',
 '5004',
 '5003',
 '5008',
 '5002',
 '5004',
 '5021',
 '5023',
 '5009',
 '5012',
 '5014',
 '5019',
 '5033',
 '5047',
 '5048',
 '5046',
 '5047',
 '5072',
 '5078',
 '5080',
 '5081',
 '5067',
 '5097',
 '5103',
 '5109',
 '5114',
 '5121',
 '5126',
 '5127',
 '5128',
 '5129',
 '5150',
 '5154',
 '5131',
 '5113',
 '5115',
 '5116',
 '5118',
 '5134',
 '5135',
 '5152',
 '5158',
 '5160',
 '5171',
 '5188',
 '5195',
 '5196',
 '5198',
 '5202',
 '5204',
 '5205',
 '5209',
 '5225',
 '5232',
 '5235',
 '5242',
 '5243',
 '5244',
 '5234',
 '5254',
 '5255',
 '5272',
 '5273',
 '5282',
 '5288',
 '5311',
 '5312',
 '5302',
 '5304',
 '5307',
 ...]

In [34]:
# here I need numbers, so convert to int
data_list = [int(x) for x in data_list]

In [35]:
df = pd.DataFrame({'values': data_list})

the question was: of all these measurements, how many are bigger than the previous measurement?  
therefore first calculate the differences, then take the sume of all of those that are larger than zero

In [19]:
differences = np.diff(df['values'].values)

In [20]:
# quick sanity check: differences should be one element shorter than the df/original data
len(df) == len(differences) +1

True

In [21]:
sum(differences > 0)

1766

then going on to **part 2**:  
it was not informative enough ;-) instead calculate sliding windows of size 3 taking the sum, and calculate from these how many are increasing

In [22]:
# first test with the example data
test_data = [199, 200, 208, 210, 200, 207, 240, 269, 260, 263]
df_test = pd.DataFrame({'test_data': test_data})

In [23]:
df_test.test_data.rolling(window=3).sum()

0      NaN
1      NaN
2    607.0
3    618.0
4    618.0
5    617.0
6    647.0
7    716.0
8    769.0
9    792.0
Name: test_data, dtype: float64

In [24]:
# with actual data
df = df.assign(rolling_sum = df['values'].rolling(window=3).sum())
df.head()

   values  rolling_sum
0     134          NaN
1     138          NaN
2     142        414.0
3     143        423.0
4     141        426.0

In [25]:
# assign differences of rolling sum to new column
df = df.assign(diff_rolling = np.nan)
df.loc[3:, 'diff_rolling'] = np.diff(df['rolling_sum'].dropna())
df.head(8)

   values  rolling_sum  diff_rolling
0     134          NaN           NaN
1     138          NaN           NaN
2     142        414.0           NaN
3     143        423.0           9.0
4     141        426.0           3.0
5     142        426.0           0.0
6     145        428.0           2.0
7     140        427.0          -1.0

In [26]:
# how many of those are larger than zero?
sum(df['diff_rolling'].dropna() > 0)

1797

yay, solved the first day! :-)